CREATE TABLE "users" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"email" TEXT NOT NULL UNIQUE,
"password" TEXT NOT NULL,
"created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)